### ISSUE TITLE
LV2/JACK versions?

### ISSUE THREAD

**Issue by mxmilkiib** [bipolaraudio/FM-BISON#115]
Are LV2 and JACK versions something that could happen in the future? [DPF](https://github.com/DISTRHO/DPF) is a framework that can target VST, LV2 and standalone JACK. It has it's own [JUCE fork](https://github.com/DISTRHO/juce) also. You also might be interested in #lad on freenode IRC server.

**Comment by visualizersdotnl** [comment]
Hi,

As it stands now we're not looking to release an example frontend (output) or our internal R&D plug-in. Simply because we're busy running this startup next to our normal lifes.

The code presented here is purely the engine or backend or however you'd like to call it. It has a Render() function that needs to be fed 2 buffers (separate ones currently, if need be interleaving wouldn't be the toughest to add) and that's where the sound goes. The code should be documented enough to read what's expected of you (start at FM_BISON.h).

At the moment things are geared towards JUCE a little bit, there are a few dependencies we're certainly looking to remove in due time. They exist purely because of pragmatism and the fact that we use the JUCE framework internally for our plug-ins (one of which is an internal R&D interface and one is due for commercial release when, well, when we're done).

What I could see happening in the future is an example app. added to this repository, firstly one simply running on an API like OpenAL. In the past I've worked on synthesizers on embedded platforms so an example in that direction (likely using ALSA or JACK which would compile on a range of lean Linux distros).

Thanks for asking and I hope this answers your question.

**Comment by visualizersdotnl** [comment]
In the interest of being transparent, here's how our current internal R&D plug-in looks (it's in beta phase). We will be releasing it to a limited selection of musicians and sound designers (and have done so in the past) to both battle test and create patches. 

What we'll do with this project long term we have not decided yet (could be a binary release, could be open source, @paulcoops and I have not discussed a scenario at this stage).

<img width="1370" alt="Beta-0 9" src="https://user-images.githubusercontent.com/1901569/85948183-b052e900-b94f-11ea-98ed-b1fee1e03f7f.PNG">
<img width="1368" alt="Beta 0 9 - #2" src="https://user-images.githubusercontent.com/1901569/85948185-b47f0680-b94f-11ea-9e0e-540e12cdc8b8.PNG">
