### ISSUE TITLE
Difference in filter cutoff frequencies

### ISSUE THREAD

**Issue by paulcoops** [bipolaraudio/FM-BISON#241]
When using the same cutoff frequency value for the main filter (low pass filter) and the post filter, the audible result is different. To display the values in Hz, both sliders use: 

 `cutoffHertzValue = SFM::SVF_CutoffToHz(float(value), unsigned(SFM::kSVFMaxFilterCutoffHz), SFM::kSVFMinFilterCutoffHz);` 

When testing with a value around 440Hz, the post filter appears to be correct but the main filter sounds lower and only starts to becomes audible around 1 kHz. Resonance is 0 in both cases.

Should I use a different Nyqist value to calculate the Hz of the main filter?

**Comment by visualizersdotnl** [comment]
I'd have to look into that. Off the cuff I'd say that first of all these are 2 comple-te-ly different filters with different characteristics, so placing them side to side and expecting the same results is off the table anyway, but maybe you're on to an inconsistency.

So in short: I'll to and take a look. Got vacation anyway until July.

**Comment by visualizersdotnl** [comment]
Also it's Nyquist Paul ;)

**Comment by visualizersdotnl** [comment]
OK,

Conclusions:
- The "waspy" double pass low pass filter was, of course, doublin' up. This means that @paulcoops 's calculations were correct but whereas the post pass filter more or less correctly cut off where you'd expect it to, the low pass would not, in fact, it would chop off Nyquist/2. Why? Because we're running it 2 damn times and we/I never really played with the parameters outside of the abstract ([0...1]) domain. Fix? Keep the wasp, also supply normal lowpass.
- Supply helper function to make it easier for clients to calculate certain value ranges; should be more intuitive, not their problem if it's 'SVF' or whatever.
- Decide if we want the wasp to actually run in twice oversampled so it doesn't have to cut off half the audible spectrum?

I @visualizersdotnl need to fix this soon and present alternatives to calculating values and using filters without breaking the interface.

**Comment by visualizersdotnl** [comment]
Closing because chat thread instead of concrete bug/issue/feature.
